
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'left+-left*/rightUMINUSCOMMENT FLOAT NAME NONDECIMAL NUMBER SCIENTIFIC SINstatement : NAME "=" expressionstatement : expressionstatement : COMMENTexpression : expression \'+\' expression\n                  | expression \'-\' expression\n                  | expression \'*\' expression\n                  | expression \'/\' expressionexpression : \'+\' expressionexpression : \'-\' expression %prec UMINUSexpression : \'(\' expression \')\'expression : SCIENTIFICexpression : SINexpression : FLOATexpression : NUMBERexpression : NONDECIMALexpression : NAMEexpression : expression COMMENT'
    
_lr_action_items = {'NAME':([0,5,6,7,13,14,15,16,17,],[2,20,20,20,20,20,20,20,20,]),'COMMENT':([0,2,3,8,9,10,11,12,18,19,20,21,22,23,24,25,26,27,28,],[4,-16,18,-11,-12,-13,-14,-15,-17,-8,-16,-9,18,18,-4,-5,-6,-7,-10,]),'+':([0,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,],[5,-16,14,5,5,5,-11,-12,-13,-14,-15,5,5,5,5,5,-17,-8,-16,-9,14,14,-4,-5,-6,-7,-10,]),'-':([0,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,],[6,-16,15,6,6,6,-11,-12,-13,-14,-15,6,6,6,6,6,-17,-8,-16,-9,15,15,-4,-5,-6,-7,-10,]),'(':([0,5,6,7,13,14,15,16,17,],[7,7,7,7,7,7,7,7,7,]),'SCIENTIFIC':([0,5,6,7,13,14,15,16,17,],[8,8,8,8,8,8,8,8,8,]),'SIN':([0,5,6,7,13,14,15,16,17,],[9,9,9,9,9,9,9,9,9,]),'FLOAT':([0,5,6,7,13,14,15,16,17,],[10,10,10,10,10,10,10,10,10,]),'NUMBER':([0,5,6,7,13,14,15,16,17,],[11,11,11,11,11,11,11,11,11,]),'NONDECIMAL':([0,5,6,7,13,14,15,16,17,],[12,12,12,12,12,12,12,12,12,]),'$end':([1,2,3,4,8,9,10,11,12,18,19,20,21,23,24,25,26,27,28,],[0,-16,-2,-3,-11,-12,-13,-14,-15,-17,-8,-16,-9,-1,-4,-5,-6,-7,-10,]),'=':([2,],[13,]),'*':([2,3,8,9,10,11,12,18,19,20,21,22,23,24,25,26,27,28,],[-16,16,-11,-12,-13,-14,-15,-17,16,-16,-9,16,16,16,16,-6,-7,-10,]),'/':([2,3,8,9,10,11,12,18,19,20,21,22,23,24,25,26,27,28,],[-16,17,-11,-12,-13,-14,-15,-17,17,-16,-9,17,17,17,17,-6,-7,-10,]),')':([8,9,10,11,12,18,19,20,21,22,24,25,26,27,28,],[-11,-12,-13,-14,-15,-17,-8,-16,-9,28,-4,-5,-6,-7,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,5,6,7,13,14,15,16,17,],[3,19,21,22,23,24,25,26,27,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> NAME = expression','statement',3,'p_statement_assign','calc.py',93),
  ('statement -> expression','statement',1,'p_statement_expr','calc.py',98),
  ('statement -> COMMENT','statement',1,'p_statement_comment','calc.py',104),
  ('expression -> expression + expression','expression',3,'p_expression_binop','calc.py',109),
  ('expression -> expression - expression','expression',3,'p_expression_binop','calc.py',110),
  ('expression -> expression * expression','expression',3,'p_expression_binop','calc.py',111),
  ('expression -> expression / expression','expression',3,'p_expression_binop','calc.py',112),
  ('expression -> + expression','expression',2,'p_expression_uplus','calc.py',124),
  ('expression -> - expression','expression',2,'p_expression_uminus','calc.py',129),
  ('expression -> ( expression )','expression',3,'p_expression_group','calc.py',134),
  ('expression -> SCIENTIFIC','expression',1,'p_expression_scientific','calc.py',139),
  ('expression -> SIN','expression',1,'p_expression_sin','calc.py',144),
  ('expression -> FLOAT','expression',1,'p_expression_float','calc.py',148),
  ('expression -> NUMBER','expression',1,'p_expression_number','calc.py',153),
  ('expression -> NONDECIMAL','expression',1,'p_expression_nondecimal','calc.py',158),
  ('expression -> NAME','expression',1,'p_expression_name','calc.py',163),
  ('expression -> expression COMMENT','expression',2,'p_expression_comment_same_line','calc.py',172),
]
